ASFLAGS_ADDITIONAL = -c -g -mcpu=cortex-m3 -mthumb -DF_CPU=84000000L -DARDUINO=10801 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM  -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER=\""Unknown\"" -DUSB_PRODUCT=\""Arduino Due\"" -D_RUNONTARGETHARDWARE_BUILD_ -D_ROTH_DUE_
TARGET_LOAD_CMD = 
TARGET_LOAD_CMD_ARGS = 
TARGET_PKG_INSTALLDIR = /home/fcuzzocrea/.matlab/SupportPackages/R2018B/toolbox/target/supportpackages/arduinotarget/registry/..
STACK_SIZE = 64
